### PR TITLE
Allow MQTT based gateways to deliver on behalf of another device

### PR DESCRIPTION
**Pull request by ctron**
As discussed in today's community call, here is the RFC for adding the ability to act on behalf of another device, when using MQTT.

Readable version: https://github.com/drogue-iot/rfcs/blob/feature/mqtt_proxy_1/active/0012-mqtt-proxy-device.md

## Open items

* [x] Command and control

### CODE REVIEW

**Comment by ctron** [comment]
The current proposal is implemented and available on `main` for testing.

**Comment by ctron** [comment]
Unless there some concerns, I would merge this PR.

**Comment by garyedwards** [comment]
Hi sorry for the slow reply on the commands side of things.  On reviewing the options the `Device in hierarchy, with a gap` seems the most intuitive from my perspective as you have selected in the proposal.

**Comment by ctron** [comment]
That is good to hear. I am currently cleanup of the RFC, taking this alternative as the proposed one.

**Pull request merged**
