### PR TITLE
Drogue cloud new API

### PR DESCRIPTION
**Pull request by jbtrystram**
This an early draft meant to spark discussion. My statements in there may be horribly wrong, please explain why ! 

[More readable document](https://github.com/drogue-iot/rfcs/blob/cloud-api/active/0006-cloud-0.5-api.adoc)

I created an open API spec only for the apps management, in order to discuss concepts and try what an API with the features i had in mind. 
See the openAPI spec in a more fancy way : https://api-drogue-api.apps.wonderful.iot-playground.org/#/

Thanks for your inputs

### CODE REVIEW

**Comment by ctron** [comment]
Taking a first look, I think the `version` information should just be hardcoded for now. I am not sure if we will have some dynamic versioning. I think having `v1` in there for now is just fine. Also using `v1alpha1` would be fine.

I don't really like the use of query parameters. I think they can be use for some options, like batch size, or format … but for the "app id", I guess having that in the path makes more sense.

I know we currently have some duplication for "update" with the app and device name. That is part of the metadata section, and there is no need to put that into the path as well.

Then again, taking look now at the "delete" and "get" operation, that looks weird as well. I think it would to do a simple `GET /api/management/app/{app}` … 

I am a bit undecided about the "bulk" operations. I think bulk operations are good. And using the "multi-status" response sounds like a great idea. It is just the path that looks a bit strange to me. Would be interesting to check how others deal with that.

**Comment by jbtrystram** [comment]
> I am a bit undecided about the "bulk" operations. I think bulk operations are good. And using the "multi-status" response sounds like a great idea. It is just the path that looks a bit strange to me. Would be interesting to check how others deal with that.

I did some reading about it because i had no idea on how to do something that made sense :D You'd be surprised to see how facebook and google deal with that ... I put the bulk operations in a separate endpoint because i wanted to try it out to get a feeling about it. 
nd have them with the regular operations without having IDs in the path I felt it would be confusing. In any case : this is early and drafty :)

**Comment by ctron** [comment]
I was thinking on how we add the "admin" operations to resources. For example, the "application" resource (not devices) need to be shared. Meaning that I want to "get" the owner, and get/update collaborators. I would somehow see this as a "sub-resource", to application. One the one side, this could fit into the metadata section … then again, having a dedicated (sub)endpoint make sense from an authorization perspective. As I would say there are multiple access levels to a resource. The following come into my mind:
* Read
* Update: edit parameters
* Admin: Delete, manage users

So having `/api/v1alpha1/apps/{app}/admin` feels like a good idea, which would have a dedicated "admin JSON", similar to the `metadata`, but more privileged.

I also know this isn't the Kubernetes style, not sure Kubernetes has something better here.

**Comment by ctron** [comment]
I think the following paths will cause issues at some point:

~~~
POST ​/api​/command​/v1alpha1​/{appId}​/{deviceId}
POST ​/api​/command​/v1alpha1​/{channel}​/{appId}​/{deviceId}
GET ​/api​/command​/v1alpha1​/inbox​/{appId}​/{deviceId}
POST ​/api​/command​/v1alpha1​/outbox​/{appId}​/{deviceId}
~~~

Basically that would lock out a "channel" being called "inbox" or "outbox" … also the only difference between the first two POST operations is just the number of path segments. Is there a chance to get a more explicit naming?

**Comment by lulf** [comment]
I agree with @ctron on the previous comment (I think), that instead of

```
POST ​/api​/command​/v1alpha1​/{appId}​/{deviceId}
```

It should be

```
POST ​/api​/command​/v1alpha1​/apps/{appId}​/device/{deviceId}
```

This is to remove any ambiguity in future API changes (and minimal changes on the client side), and it also makes it easier to read a path and immediately understand what that uuid means.

**Comment by lulf** [comment]
I'm also not sure I understand what the "bulk" API is for. Is it for batching multiple resources in requests? If so, I think it is cleaner to constraint the apps API. Either:

* Require client to do batching. This is what Kubernetes does, and seems to work well enough for bootstrapping large clusters with many resources.
* Always do batching. This is kind of like Kafka where a minimal request is a request with batch size 1. 

So: 

```
POST /api/management/v1alpha1/apps  - JSON list with apps to create
GET /api/management/v1alpha1/apps - JSON list with all apps
GET /api/management/v1alpha1/apps/myapp - JSON struct with particular app
```

I might be totally missing the point of bulk, so happy to learn what the intention is :)

**Comment by lulf** [comment]
> I was thinking on how we add the "admin" operations to resources. For example, the "application" resource (not devices) need to be shared. Meaning that I want to "get" the owner, and get/update collaborators. I would somehow see this as a "sub-resource", to application. One the one side, this could fit into the metadata section … then again, having a dedicated (sub)endpoint make sense from an authorization perspective. As I would say there are multiple access levels to a resource. The following come into my mind:
> 
>     * Read
> 
>     * Update: edit parameters
> 
>     * Admin: Delete, manage users
> 
> 
> So having `/api/v1alpha1/apps/{app}/admin` feels like a good idea, which would have a dedicated "admin JSON", similar to the `metadata`, but more privileged.
> 
> I also know this isn't the Kubernetes style, not sure Kubernetes has something better here.

I think this should be resolved by permission roles for users. Kubernetes uses roles and rolebindings here, which I think is a good model.

I think the equivalent for drogue-cloud would be for the APIs to expose some kind of role management. To grant permission, one create roles that dictate _what_ someone bound to that role can do, and then creating a binding from a user to that role. Its a bit more complex, but I think its the best approach in the long run.

```
POST /apis/admin/v1alpha1/roles - create a role
POST /apis/admin/v1alpha1/bindings - Creating a binding of a role to a user
```

The role would reference one or more applications that role should apply to and what permissions there should be.

The binding would reference a role and a user. One could just rely on some opaque identifier here that maps to the username Keycloak knows of.

A user would only be allowed to create roles and bindings if it has some admin permission I think.

Anyway, maybe its to complex... but if we're not sure what we want, I would just leave sharing applications out of scope and require that to be solved externally.

**Comment by ctron** [comment]
> Anyway, maybe its to complex... but if we're not sure what we want, I would just leave sharing applications out of scope and require that to be solved externally.

Yes, that is why I was thinking about using a model like GitHub has:

image

Where you have the resource (application) as the containing object, adding users with roles to that.

The Kubernetes RBAC model is rather complex, and I get the need for that complexity. I am just not sure if we should adopt that complexity just yet.

**Comment by jbtrystram** [comment]
> It should be
> 
> ```
> POST ​/api​/command​/v1alpha1​/apps/{appId}​/device/{deviceId}
> ```
> 
> This is to remove any ambiguity in future API changes (and minimal changes on the client side), and it also makes it easier to read a path and immediately understand what that uuid means.

It is also great as it aligns with the managment API. Good suggestion !


@lulf  
> I might be totally missing the point of bulk, so happy to learn what the intention is :)

The idea is to be able to do an operation on multiple resources in one call. e.g. in the console have a button "create devices from CSV file" and that would create all the devices in one call. 

The problems with : 
> POST /api/management/v1alpha1/apps  - JSON list with apps to create
So when i want to create 1 app i need an array of one. And I get a response of `207` which I need to parse to know if my creation is successful . It's not great as a user perspective. 

> GET /api/management/v1alpha1/apps - JSON list with all apps
> GET /api/management/v1alpha1/apps/myapp - JSON struct with particular app
Yes I agree on those and I already defined that :)

**Comment by jbtrystram** [comment]
For the commands calls that poll a command after publishing data. Could we merge that in the telemetry API and have an option ?
`POST /v1/{channel}?command-timeout=30` 
Maybe it makes thing way more complicated but just throwing the idea, if it can simplify things :)

**Comment by ctron** [comment]
> For the commands calls that poll a command after publishing data. Could we merge that in the telemetry API and have an option ?
> `POST /v1/{channel}?command-timeout=30`
> Maybe it makes thing way more complicated but just throwing the idea, if it can simplify things :)

I think we have that too (@dejanb knows better than me) … and we should have both ways …

**Comment by jbtrystram** [comment]
@lulf @ctron @dejanb  
I removed bulk operations for now (let's keep them in mind and add them on a later revision) as there is no immediate need. 
Commands now use the same pattern as the management API, and I also solved the possible mixing between `inbox`, `outbox` and  `channel`. 
To align with the managment API i used plural for devices and apps but that seem a bit weird. i am unsure about that. What do you think ?

**Comment by dejanb** [comment]
I'm completely OIK with switching parameters with paths. When we had original discussions, the issues brought up by Jens were apparent then as well. So the resolution was to go with the parameters for the moments and sync things later between two APIs. I like Ulfs proposal, so let's go with that.

As for the command API, the spec includes both "cloud" and "device" APIs under `/api/command/v1alpha1`. As JB noted `/v1/{channel}?command-timeout=30` is actually telemetry API, so maybe we should spec other device related APIs (ones going through the protocol endpoints) there and keep here only cloud-side interactions?

**Pull request merged**
